// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-c/internal/biz"
	"review-c/internal/conf"
	"review-c/internal/data"
	"review-c/internal/server"
	"review-c/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, node *conf.Node, logger log.Logger) (*kratos.App, func(), error) {
	reviewClient := data.NewGrpcClient(logger)
	dataData, cleanup, err := data.NewData(confData, logger, reviewClient)
	if err != nil {
		return nil, nil, err
	}
	consumerRepo := data.NewConsumerRepo(dataData, logger)
	consumerUsecase := biz.NewConsumerUsecase(consumerRepo, logger)
	consumerService := service.NewConsumerService(consumerUsecase)
	grpcServer := server.NewGRPCServer(confServer, consumerService, logger)
	httpServer := server.NewHTTPServer(confServer, consumerService, logger)
	consulRegistry := server.NewConsulRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, consulRegistry, node)
	return app, func() {
		cleanup()
	}, nil
}
